### ISSUE TITLE
Add Volume control

### ISSUE THREAD

**Issue by thundergreen** [definitio/ha-sox#1]
Hey! I really really love your custom component! I was searching for this for almoast 2 years now and I finally found it :) I can even play Radio Streams on it! That's awesome. The only thing is the volume control. It is on 100%. Changing for example the volume in Valetudo won't affect it as valetudo does not use SoX player. Is there any way or trick to control the volume (via Homeassistant) Or even add volume to the mediaPLayer?

**Comment by definitio** [comment]
I'll look into it. As a workaround, edit line 36 in `/usr/local/bin/sound_server.pl` on your device. Volume is set by `-v 2.0` argument.

**Comment by thundergreen** [comment]
Thanks a lot for your feedback will watch into it .. great great component
👍 and maybe soon with volume control 😃

definitio ***@***.***> schrieb am Do., 11. März 2021, 15:14:

**Comment by definitio** [comment]
[New version](https://github.com/definitio/ha-sox/releases/tag/1.1.0) is ready.
You need update sound server too. Replace content of `/usr/local/bin/sound_server.pl` with https://raw.githubusercontent.com/zvldz/vacuum/bbaca6d1a1ac148889ff7db708ae1b3fce91633f/custom-script/files/sound_server/sound_server.pl

**Comment by thundergreen** [comment]
Great 👌 works like a charm! Thanks so much.i guess it won't affect volume for valetudo sounds right as it doesn't use the same audio server

**Comment by definitio** [comment]
Yes, it's completely independent.

**Comment by Andoramb** [comment]
hm. for some reason volume changing is not working from HA

**Comment by definitio** [comment]
Show your sound_server.pl - run `cat /usr/local/bin/sound_server.pl` and paste output.
P.S.: please create a new issue next time.

**Comment by Andoramb** [comment]
sorry, I'm using the same sound_server script as mentioned above (or as it is in the repo).
Oh right, it's working but the volume can be set only upon startup. Didn't know that. thanks!
